### ISSUE TITLE
Why WisePDF???

### ISSUE THREAD

**Issue by asishtripathy** [igor-alexandrov/wisepdf#16]
As far as i have understood the gem, i can see that it is exactly the same as WickedPDF except the nam/e(wisepdf and wicked_pdf). can anyone tell me the difference between these two gems? It will be good to know the extra features offered by wisepdf.

Thanks in advance.

**Comment by igor-alexandrov** [comment]
When I started wisepdf I spent more then one day modifying WickedPDF code and fixing a lot of bugs.
Checkout code to see difference.
