### ISSUE TITLE
Page Numbers Broken In 1.2.9

### ISSUE THREAD

**Issue by abstractcoder** [igor-alexandrov/wisepdf#17]
The recent change in parameter escaping seems to have broken the automatic page numbers. Here is my initializer:

``` ruby
Wisepdf::Configuration.configure do |c|
  c.options = {
    :footer => { 
      :center => "[page] of [topage]",
      :font_size => 10,
    }
  }
end
```

Here is the output:

![Screen Shot 2013-03-08 at 10 30 57 AM](https://f.cloud.github.com/assets/455414/237224/cdc06d3a-880d-11e2-9232-b33e2741a94e.png)

Rolling back to 1.2.8 fixes the issue.

**Comment by igor-alexandrov** [comment]
Fixed in 1.2.10.
Thanks!
