### ISSUE TITLE
NameError (undefined local variable or method `options' 

### ISSUE THREAD

**Issue by gustavo43t** [igor-alexandrov/wisepdf#5]
Igor,

in render.rb, method prerender_header_and_footer,

``` ruby
# options[hf][:html] = "file://#{tf.path}" 
# must be
arguments[hf][:html] = "file://#{tf.path}" 
```

and thanks for your work!

**Comment by igor-alexandrov** [comment]
Fixed in wisepdf 1.2.0.
Sorry for 1.1.x release it was a hotfix for my internal needs.
